name: appinfluencers
region: nyc

# Database (MySQL managed by Digital Ocean)
databases:
  - name: db-mysql
    engine: MYSQL
    version: "8"
    production: true
    cluster_name: appinfluencers-db

# Backend API Service
services:
  - name: api
    github:
      repo: dcastill92/appinfluencers
      branch: main
      deploy_on_push: true
    source_dir: /app
    dockerfile_path: /Dockerfile
    
    http_port: 8000
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    envs:
      # Database - will be injected by Digital Ocean
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db-mysql.DATABASE_URL}
      
      # Security - IMPORTANT: Change SECRET_KEY in production
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "CHANGE_THIS_IN_PRODUCTION_USE_STRONG_SECRET"
      
      - key: ALGORITHM
        scope: RUN_TIME
        value: "HS256"
      
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "480"
      
      # Trial Configuration
      - key: TRIAL_DURATION_HOURS
        scope: RUN_TIME
        value: "24"
      
      # Stripe Configuration - Add your production keys
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "sk_live_YOUR_STRIPE_SECRET_KEY"
      
      - key: STRIPE_PUBLISHABLE_KEY
        scope: RUN_TIME
        value: "pk_live_YOUR_STRIPE_PUBLISHABLE_KEY"
      
      - key: PLATFORM_COMMISSION_RATE
        scope: RUN_TIME
        value: "0.15"
      
      # Social Media APIs
      - key: FACEBOOK_APP_ID
        scope: RUN_TIME
        value: "1531422201378331"
      
      - key: FACEBOOK_APP_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "67e9b81b1ae62703dd9f45417ff4d548"
      
      - key: INSTAGRAM_ACCESS_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: "YOUR_INSTAGRAM_ACCESS_TOKEN"
      
      - key: TIKTOK_CLIENT_KEY
        scope: RUN_TIME
        value: ""
      
      - key: TIKTOK_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: ""
      
      # Email Configuration (Optional)
      - key: SMTP_HOST
        scope: RUN_TIME
        value: "smtp.gmail.com"
      
      - key: SMTP_PORT
        scope: RUN_TIME
        value: "587"
      
      - key: SMTP_USER
        scope: RUN_TIME
        value: "your-email@gmail.com"
      
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "your-app-password"
      
      # Application
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"
      
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
    
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    run_command: |
      alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000

  # Frontend Service
  - name: frontend
    github:
      repo: dcastill92/appinfluencers
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    dockerfile_path: /frontend/Dockerfile
    
    http_port: 3000
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    build_command: npm run build
    
    envs:
      # Backend API URL (internal communication)
      - key: BACKEND_INTERNAL_URL
        scope: RUN_TIME
        value: ${api.PRIVATE_URL}
      
      # Public API URL (for client-side requests)
      - key: NEXT_PUBLIC_API_URL
        scope: BUILD_TIME
        value: ${api.PUBLIC_URL}
      
      # Facebook App ID
      - key: NEXT_PUBLIC_FACEBOOK_APP_ID
        scope: BUILD_TIME
        value: "1531422201378331"
      
      - key: NODE_ENV
        scope: RUN_TIME
        value: "production"
    
    routes:
      - path: /
